syntax = "proto3";

package chats.v1;

import "chats_types.proto";

service ChatsService {
    rpc CreateGroupChat(CreateGroupChatRequest) returns (ChatResponse);
    rpc CreateDirectChat(CreateDirectChatRequest) returns (ChatResponse);
    rpc GetChatByID(GetChatByIDRequest) returns (GetChatResponse);
    rpc GetChatByName(GetChatByNameRequest) returns (GetChatResponse);
    rpc UpdateChat(UpdateChatRequest) returns (ChatResponse);
    rpc DeleteChat(DeleteChatRequest) returns (ChatResponse);

    rpc AddParticipant(AddParticipantRequest) returns (ParticipantResponse);
    rpc RemoveParticipant(RemoveParticipantRequest) returns (ParticipantResponse);
    rpc ListParticipants(ListParticipantsRequest) returns (ListParticipantsResponse);
    rpc CheckParticipant(CheckParticipantRequest) returns (CheckParticipantResponse);

    rpc ListChatsForUser(ListChatsForUserRequest) returns (ListChatsForUserResponse);
    rpc ListAvatarsForChats(ListAvatarsForChatsRequest) returns (ListAvatarsForChatsResponse);
}

message CreateGroupChatRequest {
    string name = 1;
    string about = 2;
    Avatar avatar = 3;
}

message CreateDirectChatRequest {
    string user_id = 1;
}

message UpdateChatRequest {
    Chat chat = 1;
    Avatar avatar = 2;
}

message DeleteChatRequest {
    string chat_id = 1;
}

message GetChatByIDRequest {
    string chat_id = 1;
}

message GetChatByNameRequest {
    string name = 1;
}

message GetChatResponse {
    Chat chat = 1;
}

message ChatResponse {
    Chat chat = 1;
    Avatar avatar = 2; // optional
}

message ListChatsForUserRequest {
    string user_id = 1;
}

message ListChatsForUserResponse {
    repeated Chat chats = 1;
}

message AddParticipantRequest {
    string chat_id = 1;
    string user_id = 2;
    ChatParticipantRole role = 3;
}

message RemoveParticipantRequest {
    string user_id = 1;
    string chat_id = 2;
}

message ParticipantResponse {
    bool ok = 1;
}

message ListParticipantsRequest {
    string chat_id = 1;
}

message ListParticipantsResponse {
    repeated ChatParticipant users = 1;
}

message CheckParticipantRequest {
    string chat_id = 1;
    string user_id = 2;
}

message CheckParticipantResponse {
    bool is_participant = 1;
    ChatParticipantRole role = 2;
}

message ListAvatarsForChatsRequest {
    repeated ChatSummary chats = 1;
}

message ListAvatarsForChatsResponse {
    repeated Avatar avatars = 1;
}
